### ISSUE TITLE
 phys2bids No module named 'phys2bids.physiobids'

### ISSUE THREAD

**Issue by sento4000** [smoia/phys2bids#21]
Hi guys,

So I basically installed all the modules required for phys2bids in python3 and executed with python3 the setup.py file and when I tried the command from the console this funny error came out: 
phys2bids
Traceback (most recent call last):
  File "/usr/local/bin/phys2bids", line 11, in <module>
    load_entry_point('phys2bids==0.4.0', 'console_scripts', 'phys2bids')()
  File "/home/vicente/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/vicente/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/home/vicente/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/home/vicente/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'phys2bids.physiobids'
I have no absolute idea why is this happenning.

First problem

**Comment by sento4000** [comment]
Okay I think is because for some reason my phys2bids module does not contain the function physiobids. Any idea why this is happening?

**Comment by smoia** [comment]
Can you pull again and tell me if it works?

**Comment by sento4000** [comment]
I see what you did there,

It seems to be working properly now, this is the output:
phys2bids
usage: phys2bids [-h] -in FILENAME [-info] [-indir INDIR] [-outdir OUTDIR]
                 [-heur HEUR_FILE] [-sub SUB] [-ses SES] [-chtrig CHTRIG]
                 [-chsel [CHSEL [CHSEL ...]]] [-ntp NUM_TPS_EXPECTED] [-tr TR]
                 [-thr THR] [-tbhd [TABLE_HEADER [TABLE_HEADER ...]]] [-v]
phys2bids: error: the following arguments are required: -in/--input-file
I think we can close this issue

**Comment by smoia** [comment]
Closed by commit 8ff5bf0f5fd2982417854932fded4a0f5e970e19
