### ISSUE TITLE
Add all-contributors to this repo

### ISSUE THREAD

**Issue by smoia** [smoia/phys2bids#46]

**Comment by eurunuela** [comment]
@smoia given that you requested the bot, will you continue work on this issue?

**Comment by smoia** [comment]
yep, I'm on it!

**Comment by smoia** [comment]
@all-contributors please add @smoia for code, ideas, infra, maintenance, projectManagement, review

**Comment by smoia** [comment]
@all-contributors pretty please add @smoia for doc

**Comment by smoia** [comment]
@all-contributors pretty pretty please add @rmarkello for bug, code, ideas, infra, review, test, then add @vinferrer for bug, code, doc, review.

**Comment by smoia** [comment]
@all-contributors pretty pretty please add @rmarkello for bug, code, ideas, infra, review, test

**Comment by smoia** [comment]
add @vinferrer for bug, code, doc, review.

**Comment by smoia** [comment]
Closing due to bot malfunction
