### ISSUE TITLE
Add license info in files

### ISSUE THREAD

**Issue by smoia** [smoia/phys2bids#5]
Add info about the license in all the main files, as per the end of the GNUv3 license

**Comment by MinchinWeb** [comment]
Do you want the full license text, or just that the file is under GNUv3?

**Comment by smoia** [comment]
It should be following all the specifications [from line 623 to the last line of the licence](https://github.com/smoia/phys2bids/blob/c7976275787f6c6ad637dfb5dbc081de05ccefd9/LICENSE#L623)
